### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by jianping0222** [pganalyze/libpg_query#205] opened 2023-08-18 08:04 UTC
libpg_query Can support Windows？yes or no？

**Comment by lelit** [comment] 2023-08-18 08:24
This is a duplicate of #44: there you can find several answers, that basically say "yes, it would be desiderable and even doable, provided someone could spend the required time in investigating and implementing such thing".

**Comment by lfittl** [comment] 2023-08-18 17:23
Closing since its a duplicate, thanks @lelit for responding as well :)

**Closed as completed by lfittl** 2023-08-18 17:23 UTC
