### ISSUE TITLE
Segmentation fault on invalid input to scan()

### ISSUE THREAD

**Issue by lelit** [pganalyze/libpg_query#108] opened 2021-05-14 08:53 UTC
By chance, it happened that I did pass an invalid input to the `scan()` function, and got a segmentation error. Could not investigate further yet, but this is a quick reproducing recipe:

```diff
diff --git a/examples/scan.c b/examples/scan.c
index 41d0e94..be9e9ac 100644
--- a/examples/scan.c
+++ b/examples/scan.c
@@ -6,7 +6,7 @@
 
 size_t testCount = 12;
 const char* tests[] = {
-  "SELECT 1",
+  "SELECT \\s 1",
   "SELECT * FROM x WHERE z = 2",
   "SELECT 5.41414",
   "SELECT $1",
```

```
$ make examples
$ examples/scan 
SELECT \s 1
  version: 130002, tokens: 4, size: 39
  "SELECT" = [ 0, 6, SELECT, RESERVED_KEYWORD ]
Segmentation fault
```

**Comment by lfittl** [comment] 2021-05-15 07:03
@lelit Looks like this is caused by ASCII character 92 (`\`) not being in the protobuf token list - I think thats an oversight on my part: https://github.com/pganalyze/libpg_query/blob/13-latest/protobuf/pg_query.proto#L3014

You could make it work by just ignoring token_kind being null, like this:

```diff
diff --git a/examples/scan.c b/examples/scan.c
index 41d0e94..bd3d632 100644
--- a/examples/scan.c
+++ b/examples/scan.c
@@ -4,9 +4,10 @@
 
 #include "protobuf/pg_query.pb-c.h"
 
-size_t testCount = 12;
+size_t testCount = 13;
 const char* tests[] = {
   "SELECT 1",
+  "SELECT \\s 1",
   "SELECT * FROM x WHERE z = 2",
   "SELECT 5.41414",
   "SELECT $1",
@@ -43,7 +44,7 @@ int main() {
         scan_token = scan_result->tokens[j];
         token_kind = protobuf_c_enum_descriptor_get_value(&pg_query__token__descriptor, scan_token->token);
         keyword_kind = protobuf_c_enum_descriptor_get_value(&pg_query__keyword_kind__descriptor, scan_token->keyword_kind);
-        printf("  \"%.*s\" = [ %d, %d, %s, %s ]\n", scan_token->end - scan_token->start, &(tests[i][scan_token->start]), scan_token->start, scan_token->end, token_kind->name, keyword_kind->name);
+        printf("  \"%.*s\" = [ %d, %d, %s, %s ]\n", scan_token->end - scan_token->start, &(tests[i][scan_token->start]), scan_token->start, scan_token->end, token_kind != NULL ? token_kind->name : "UNKNOWN", keyword_kind->name);
       }
```

(but the actual fix here requires adjusting the protobuf definition - I can take care of that)

**Comment by lelit** [comment] 2021-05-15 07:17
Right, just reached the same :-)

**Comment by lfittl** [comment] 2021-06-24 21:01
Fixed in https://github.com/pganalyze/libpg_query/pull/109

**Closed as completed by lfittl** 2021-06-24 21:01 UTC
