### ISSUE TITLE
pg_query_parse fails to parse valid SQL statement

### ISSUE THREAD

**Issue by svenklemm** [pganalyze/libpg_query#132] opened 2022-04-15 10:58 UTC
The following query fails with `syntax error at or near "?", at index 17`
```
CREATE OPERATOR #? (LEFTARG=bool,RIGHTARG=bool,FUNCTION=boolge);
```
In postgresql 13 this query runs without problems.

**Comment by lfittl** [comment] 2022-04-19 06:27
@svenklemm Ah, interesting - I think the root cause here is the parser patch that supports treating `?` as param refs, for compatibility with pg_stat_statements query texts on Postgres 9.6 and older (https://github.com/pganalyze/libpg_query/blob/13-latest/patches/02_parser_support_question_mark_as_param_ref.patch)

Since Postgres 9.6 is EOL now, it seems reasonable to drop this patch altogether in the next major libpg_query release (i.e. the one targeting Postgres 14).

Is this part of an extension you are using, or a custom operator in your environment?

We do have special exclusion for certain commonly used operators, and so we could add it there, ahead of dropping the patch altogether: https://github.com/pganalyze/libpg_query/blob/13-latest/patches/02_parser_support_question_mark_as_param_ref.patch#L303

**Comment by svenklemm** [comment] 2022-04-19 11:21
Thanks for the pointer. The promscale extension defines a `#?` operator: https://github.com/timescale/promscale/blob/master/pkg/migrations/sql/idempotent/tracing-tags.sql#L51

**Comment by lfittl** [comment] 2022-04-20 00:52
@svenklemm Thanks for the PR - merged!

**Closed as completed by lfittl** 2022-04-20 00:52 UTC
