### ISSUE TITLE
What is missing to be able to fully parse PL/pgSQL functions?

### ISSUE THREAD

**Issue by juliendelplanque** [pganalyze/libpg_query#39] opened 2017-10-06 19:17 UTC
Hello,

First of all thanks a lot for this amazing project. :-)

I really need a fully functional parser for PostgreSQL and PL/pgSQL for my PhD.
Can you summarise what is missing and eventually give me pointers to how to do it?

I may help to finish the parser but I can not promise, it depends on the effort to provide.

I have examples of PL/pgSQL code from a real database that the parser can not handle yet.

Thanks in advance,

Julien

**Comment by lfittl** [comment] 2017-10-06 23:20
Hi Julien,

I recently wrote a comment here that details some of it: https://github.com/lfittl/libpg_query/issues/38#issuecomment-331649532

Essentially the problem is that the way we call into the PL/pgSQL parser doesn't support everything yet. This may simply be a matter of writing some C code, but will most likely require going a bit into the depths of Postgres itself.

In particular I worry that we might need to stub a few more methods, to make the server act as if it was a library. You can see the existing mocks we apply for query parsing and PL/pgSQL here: https://github.com/lfittl/libpg_query/blob/9.5-latest/scripts/extract_source.rb#L438

Does that make sense?

If you'd like to see progress faster the best way is to dive into the code and fix some failing test cases. Let me know if you run into any issues on the mocking/patching side of things :)

**Comment by langpavel** [comment] 2017-11-08 20:11
> I have examples of PL/pgSQL code from a real database that the parser can not handle yet.

Main reason is probably that functions and `DO` blocks are not part of grammar itself, instead Postgres delegates this to dynamic libraries for each language. [Look here for other languages](https://github.com/postgres/postgres/tree/master/src/pl)

**Comment by lfittl** [comment] 2017-11-08 21:37
@langpavel Yup - libpg_query currently has limited support for PL/pgSQL parsing, separately from the query parsing, see https://github.com/lfittl/libpg_query#usage-parsing-a-plpgsql-function-experimental

Unfortunately as mentioned above the PL/pgSQL parser is a bit more dependent on things that are usually present in a properly initialized and running Postgres server (e.g. data types) which makes the work of extracting that parser into a library a bit more tricky.

**Comment by lfittl** [comment] 2018-04-08 17:50
Noting this commit in Postgres 11 that may be useful to provide catalog types: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=372728b0d49552641f0ea83d9d2e08817de038fa

The thought is to maybe parse the new `.dat` files and provide the required base type information from that. Its still going to be quite some work to wire things up of course.

**Comment by lfittl** [comment] 2021-10-09 00:52
Most known issues are fixed in https://github.com/pganalyze/libpg_query/commit/e9e4ba9ffcbac02bce6656ecabd22c2b54eca1b2 (its likely that any other issues would actually require a more comprehensive data type handling, as discussed)

**Closed as completed by lfittl** 2021-10-09 00:52 UTC
